# Example configuration for data_capture_tools
output_root: /mnt/nvme1/tsumura/dicomo/after_dicomo_data_test
task_name: test
prompt: ""
label: "かちかち, kachi-kachi" #"ふかふか, huka-huka", "かちかち, kachi-kachi", "ぷにぷに, puni-puni", "ぷりぷり, puri-puri", "ふわふわ, huwa-huwa"
# "つるつる, tsuru-tsuru", "ぺたぺた, peta-peta", "さらさら, sara-sara", "ざらざら, zara-zara", "すべすべ, sube-sube", "ふさふさ, husa-husa", "もこもこ, moko-moko", "べたべた, beta-beta", "ねばねば, neba-neba", "ひんやり, hin-yari", "あつあつ, ats-atsu", "かちかち, kachi-kachi", "ぷにぷに, puni-puni", "ぷりぷり, puri-puri", "ふわふわ, huwa-huwa"
# 基本姿勢
initial_arm_pose: [99.42, -80.95, 73.53, -82.98, -90.77, 54.60]
# 基準座標（メートル単位）
base_tcp_pose:
  x: 0.16823
  y: -0.31254
  z: -0.06175
  rx: 1.200
  ry: 2.919
  rz: -0.030
# 実験パラメータ
target_diameter: 0.038 # 物体幅 (mm) #クランプの幅を参照
gripper_offset: 0.000 # デバイス誤差 (mm)
arm_offset: 0.0025 # アームの位置誤差 (mm)
push_depth: 0.002 # 押し込み量 (mm)
viewer_topics:
  - /camera_fixed/realsense2_camera/color/image_raw
  - /camera_wrist/realsense2_camera/color/image_raw
image_throttle_hz: 0
other_throttle_hz: 0
enable_image_compression: true
stop_key: q
bag_record:
  storage: sqlite3
  compression_mode: file
  compression_format: zstd
topics:
  - name: /camera_wrist/realsense2_camera/color/image_raw
    type: sensor_msgs/msg/Image
    mode: image
    encoding: bgr8
  - name: /camera_fixed/realsense2_camera/color/image_raw
    type: sensor_msgs/msg/Image
    mode: image
    encoding: bgr8
  - name: /gelsight/left/image_raw
    type: sensor_msgs/msg/Image
    mode: image
    encoding: bgr8
  - name: /gelsight/right/image_raw
    type: sensor_msgs/msg/Image
    mode: image
    encoding: bgr8
  - name: /tf
    type: tf2_msgs/msg/TFMessage
    mode: csv
  - name: /tf_static
    type: tf2_msgs/msg/TFMessage
    mode: csv
  - name: /joint_states
    type: sensor_msgs/msg/JointState
    mode: csv
  - name: /scaled_joint_trajectory_controller/controller_state
    type: control_msgs/msg/JointTrajectoryControllerState
    mode: csv
  - name: /scaled_joint_trajectory_controller/joint_trajectory
    type: trajectory_msgs/msg/JointTrajectory
    mode: csv
  - name: /forward_position_controller/commands
    type: std_msgs/msg/Float64MultiArray
    mode: csv
  - name: /robotiq_2f_gripper/finger_distance_mm
    type: std_msgs/msg/Float32
    mode: csv
  - name: /robotiq_2f_gripper_action_goal
    type: std_msgs/msg/Float32MultiArray
    mode: csv
  - name: /force_torque/left
    type: geometry_msgs/msg/WrenchStamped
    mode: csv
  - name: /force_torque/right
    type: geometry_msgs/msg/WrenchStamped
    mode: csv
    # --- 以下の 3 行を追記 ---
  - name: /trial_marker
    type: std_msgs/msg/String
    mode: csv
